version: '3.7'

services:
    lavalink:
        image: fredboat/lavalink:dev
        container_name: lavalink_1
        restart: unless-stopped
        volumes:
            - ./application.yml:/opt/Lavalink/application.yml
        networks:
            - lavalink
        expose:
            - 2333
    Bebotpy:
        image: halfblood1223/bebot:v1.3
        container_name: bebotpy
        restart: unless-stopped
        networks:
            - bebot-network
            - lavalink
        depends_on: 
            - lavalink
        environment:
            - lavahost=lavalink
networks:
    lavalink:
        name: lavalink
    bebot-network:
        name: bebot-network